# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

matrixDim <- function(data) {
    .Call(`_eggcount_matrixDim`, data)
}

rcpp_hello_world <- function(inputT) {
    .Call(`_eggcount_rcpp_hello_world`, inputT)
}

CreateDistImage <- function(values, ncols, nrows) {
    .Call(`_eggcount_CreateDistImage`, values, ncols, nrows)
}

FindEdgePoints <- function(distance, ncols, nrows, centX, centY) {
    .Call(`_eggcount_FindEdgePoints`, distance, ncols, nrows, centX, centY)
}

